data:
  path: data/creditcard.csv
  target: Class


cv:
  strategy: StratifiedKFold
  n_splits: 5
  shuffle: true
  random_state: 42


sampling:
  type: RandomUnderSampler
  search_space:
    sampling_strategy:
      - 0.01
      - 0.05
      - 0.1
      - 0.2


grid_search:
  scoring: f1
  n_jobs: -1
  verbose: 1
  refit: true


models:

  logistic_regression:
    fixed_params:
      solver: lbfgs
      max_iter: 3000

    search_space:
      C:
        - 0.00001
        - 0.0001
        - 0.001
        - 0.01
        - 0.1
        - 1
        - 10
      class_weight:
        - null
        - balanced

  random_forest:
    fixed_params:
      random_state: 42
      n_jobs: -1

    search_space:
      n_estimators: [50, 100]      
      max_depth: [5, 10]            
      min_samples_split: [2, 5]     
      min_samples_leaf: [1, 2]


   


       